import Foundation
import SwiftUI

@MainActor
final class Store: ObservableObject {
    @Published var tunnels: [Tunnel] = []
    let runner: TunnelRunner

    private let supportDir: URL
    private let configURL: URL
    private let askpassURL: URL

    init() {
        let base = FileManager.default
            .urls(for: .applicationSupportDirectory, in: .userDomainMask)[0]
            .appendingPathComponent("TunnelBar", isDirectory: true)
        try? FileManager.default.createDirectory(at: base, withIntermediateDirectories: true)
        supportDir = base
        configURL = base.appendingPathComponent("tunnels.json")
        askpassURL = base.appendingPathComponent("askpass.sh")

        runner = TunnelRunner(askpassPath: askpassURL.path)
        installAskpass()
        load()
    }

    // MARK: - Persistence

    private func load() {
        if let data = try? Data(contentsOf: configURL),
           let decoded = try? JSONDecoder().decode([Tunnel].self, from: data) {
            tunnels = decoded
        } else {
            tunnels = [Tunnel.seed()]
            save()
        }
        // Autostart on launch.
        for t in tunnels where t.autostart && Keychain.hasPassword(account: t.keychainAccount) {
            runner.start(t)
        }
    }

    func save() {
        guard let data = try? JSONEncoder().encode(tunnels) else { return }
        try? data.write(to: configURL, options: .atomic)
    }

    // MARK: - Mutations

    func addTunnel() -> UUID {
        var t = Tunnel()
        t.name = "New Tunnel"
        tunnels.append(t)
        save()
        return t.id
    }

    func delete(_ id: UUID) {
        runner.stop(id)
        Keychain.deletePassword(account: id.uuidString)
        tunnels.removeAll { $0.id == id }
        save()
    }

    func binding(for id: UUID) -> Binding<Tunnel>? {
        guard tunnels.contains(where: { $0.id == id }) else { return nil }
        return Binding(
            // Resolve the index lazily on every access. Capturing a fixed index
            // crashes when the array shrinks (e.g. after deleting a tunnel) and
            // SwiftUI re-evaluates the stale binding during the same update.
            get: {
                guard let idx = self.tunnels.firstIndex(where: { $0.id == id }) else {
                    return Tunnel()
                }
                return self.tunnels[idx]
            },
            set: { newValue in
                guard let idx = self.tunnels.firstIndex(where: { $0.id == id }) else { return }
                self.tunnels[idx] = newValue
            }
        )
    }

    // MARK: - askpass helper

    /// Writes a tiny shell helper that ssh calls to obtain the password from Keychain.
    private func installAskpass() {
        let script = """
        #!/bin/sh
        # Auto-generated by TunnelBar. Returns the stored password for the active tunnel.
        exec /usr/bin/security find-generic-password \
          -s "$TUNNELBAR_KEYCHAIN_SERVICE" \
          -a "$TUNNELBAR_KEYCHAIN_ACCOUNT" -w
        """
        try? script.write(to: askpassURL, atomically: true, encoding: .utf8)
        try? FileManager.default.setAttributes(
            [.posixPermissions: 0o700], ofItemAtPath: askpassURL.path)
    }
}
